[project]
site_name = "ClamAV on Alpine Docker"
site_description = "A lightweight ClamAV Docker image based on Alpine Linux."
site_author = "TQ"
copyright = "&copy; 2025 TQ. All rights reserved."
repo_url = "https://github.com/tquizzle/clamav-alpine/"
[project.theme]
logo = "img/clamav-docker-removebg-preview.png"
favicon = "img/clamav-docker.ico"
[project.extra]
generator = true
[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/tquizzle"
[project.markdown_extensions.admonition]
[project.markdown_extensions.tables]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]